//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Tesi", "FilesOFOrder", "Ordine", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(KiLab.Models.Ordine), "File", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KiLab.Models.File), true)]
[assembly: EdmRelationshipAttribute("Tesi", "RilegaturaOrdine", "Rilegatura", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(KiLab.Models.Rilegatura), "Ordine", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KiLab.Models.Ordine), true)]
[assembly: EdmRelationshipAttribute("Tesi", "SpedizioneOrdine", "Spediz", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(KiLab.Models.Spediz), "Ordine", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KiLab.Models.Ordine), true)]

#endregion

namespace KiLab.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TesiContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TesiContainer object using the connection string found in the 'TesiContainer' section of the application configuration file.
        /// </summary>
        public TesiContainer() : base("name=TesiContainer", "TesiContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TesiContainer object.
        /// </summary>
        public TesiContainer(string connectionString) : base(connectionString, "TesiContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TesiContainer object.
        /// </summary>
        public TesiContainer(EntityConnection connection) : base(connection, "TesiContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<File> File
        {
            get
            {
                if ((_File == null))
                {
                    _File = base.CreateObjectSet<File>("File");
                }
                return _File;
            }
        }
        private ObjectSet<File> _File;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Logs> Logs
        {
            get
            {
                if ((_Logs == null))
                {
                    _Logs = base.CreateObjectSet<Logs>("Logs");
                }
                return _Logs;
            }
        }
        private ObjectSet<Logs> _Logs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Rilegatura> Rilegatura
        {
            get
            {
                if ((_Rilegatura == null))
                {
                    _Rilegatura = base.CreateObjectSet<Rilegatura>("Rilegatura");
                }
                return _Rilegatura;
            }
        }
        private ObjectSet<Rilegatura> _Rilegatura;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Spediz> Spediz
        {
            get
            {
                if ((_Spediz == null))
                {
                    _Spediz = base.CreateObjectSet<Spediz>("Spediz");
                }
                return _Spediz;
            }
        }
        private ObjectSet<Spediz> _Spediz;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ordine> Ordine
        {
            get
            {
                if ((_Ordine == null))
                {
                    _Ordine = base.CreateObjectSet<Ordine>("Ordine");
                }
                return _Ordine;
            }
        }
        private ObjectSet<Ordine> _Ordine;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the File EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFile(File file)
        {
            base.AddObject("File", file);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Logs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLogs(Logs logs)
        {
            base.AddObject("Logs", logs);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Rilegatura EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRilegatura(Rilegatura rilegatura)
        {
            base.AddObject("Rilegatura", rilegatura);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Spediz EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSpediz(Spediz spediz)
        {
            base.AddObject("Spediz", spediz);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ordine EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrdine(Ordine ordine)
        {
            base.AddObject("Ordine", ordine);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Tesi", Name="File")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class File : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new File object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static File CreateFile(global::System.Int32 id)
        {
            File file = new File();
            file.Id = id;
            return file;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PercorsoFisico
        {
            get
            {
                return _PercorsoFisico;
            }
            set
            {
                OnPercorsoFisicoChanging(value);
                ReportPropertyChanging("PercorsoFisico");
                _PercorsoFisico = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PercorsoFisico");
                OnPercorsoFisicoChanged();
            }
        }
        private global::System.String _PercorsoFisico;
        partial void OnPercorsoFisicoChanging(global::System.String value);
        partial void OnPercorsoFisicoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Note
        {
            get
            {
                return _Note;
            }
            set
            {
                OnNoteChanging(value);
                ReportPropertyChanging("Note");
                _Note = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Note");
                OnNoteChanged();
            }
        }
        private global::System.String _Note;
        partial void OnNoteChanging(global::System.String value);
        partial void OnNoteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Stampato
        {
            get
            {
                return _Stampato;
            }
            set
            {
                OnStampatoChanging(value);
                ReportPropertyChanging("Stampato");
                _Stampato = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Stampato");
                OnStampatoChanged();
            }
        }
        private Nullable<global::System.Boolean> _Stampato;
        partial void OnStampatoChanging(Nullable<global::System.Boolean> value);
        partial void OnStampatoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Bozza
        {
            get
            {
                return _Bozza;
            }
            set
            {
                OnBozzaChanging(value);
                ReportPropertyChanging("Bozza");
                _Bozza = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Bozza");
                OnBozzaChanged();
            }
        }
        private Nullable<global::System.Boolean> _Bozza;
        partial void OnBozzaChanging(Nullable<global::System.Boolean> value);
        partial void OnBozzaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Eliminato
        {
            get
            {
                return _Eliminato;
            }
            set
            {
                OnEliminatoChanging(value);
                ReportPropertyChanging("Eliminato");
                _Eliminato = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Eliminato");
                OnEliminatoChanged();
            }
        }
        private Nullable<global::System.Boolean> _Eliminato;
        partial void OnEliminatoChanging(Nullable<global::System.Boolean> value);
        partial void OnEliminatoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DimensioneKb
        {
            get
            {
                return _DimensioneKb;
            }
            set
            {
                OnDimensioneKbChanging(value);
                ReportPropertyChanging("DimensioneKb");
                _DimensioneKb = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DimensioneKb");
                OnDimensioneKbChanged();
            }
        }
        private Nullable<global::System.Int32> _DimensioneKb;
        partial void OnDimensioneKbChanging(Nullable<global::System.Int32> value);
        partial void OnDimensioneKbChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OrdineID
        {
            get
            {
                return _OrdineID;
            }
            set
            {
                OnOrdineIDChanging(value);
                ReportPropertyChanging("OrdineID");
                _OrdineID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrdineID");
                OnOrdineIDChanged();
            }
        }
        private Nullable<global::System.Int32> _OrdineID;
        partial void OnOrdineIDChanging(Nullable<global::System.Int32> value);
        partial void OnOrdineIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Data
        {
            get
            {
                return _Data;
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private Nullable<global::System.DateTime> _Data;
        partial void OnDataChanging(Nullable<global::System.DateTime> value);
        partial void OnDataChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Tesi", "FilesOFOrder", "Ordine")]
        public Ordine Ordine
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ordine>("Tesi.FilesOFOrder", "Ordine").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ordine>("Tesi.FilesOFOrder", "Ordine").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ordine> OrdineReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ordine>("Tesi.FilesOFOrder", "Ordine");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ordine>("Tesi.FilesOFOrder", "Ordine", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Tesi", Name="Logs")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Logs : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Logs object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Logs CreateLogs(global::System.Int64 id)
        {
            Logs logs = new Logs();
            logs.Id = id;
            return logs;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Testo
        {
            get
            {
                return _Testo;
            }
            set
            {
                OnTestoChanging(value);
                ReportPropertyChanging("Testo");
                _Testo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Testo");
                OnTestoChanged();
            }
        }
        private global::System.String _Testo;
        partial void OnTestoChanging(global::System.String value);
        partial void OnTestoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Data
        {
            get
            {
                return _Data;
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private Nullable<global::System.DateTime> _Data;
        partial void OnDataChanging(Nullable<global::System.DateTime> value);
        partial void OnDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CodEx
        {
            get
            {
                return _CodEx;
            }
            set
            {
                OnCodExChanging(value);
                ReportPropertyChanging("CodEx");
                _CodEx = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CodEx");
                OnCodExChanged();
            }
        }
        private global::System.String _CodEx;
        partial void OnCodExChanging(global::System.String value);
        partial void OnCodExChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Tesi", Name="Ordine")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ordine : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ordine object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="bozzaAcquistata">Initial value of the BozzaAcquistata property.</param>
        /// <param name="cartaPlus">Initial value of the CartaPlus property.</param>
        /// <param name="fronteRetro">Initial value of the FronteRetro property.</param>
        public static Ordine CreateOrdine(global::System.Int32 id, global::System.Boolean bozzaAcquistata, global::System.Boolean cartaPlus, global::System.Boolean fronteRetro)
        {
            Ordine ordine = new Ordine();
            ordine.Id = id;
            ordine.BozzaAcquistata = bozzaAcquistata;
            ordine.CartaPlus = cartaPlus;
            ordine.FronteRetro = fronteRetro;
            return ordine;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Data
        {
            get
            {
                return _Data;
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private Nullable<global::System.DateTime> _Data;
        partial void OnDataChanging(Nullable<global::System.DateTime> value);
        partial void OnDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Token
        {
            get
            {
                return _Token;
            }
            set
            {
                OnTokenChanging(value);
                ReportPropertyChanging("Token");
                _Token = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Token");
                OnTokenChanged();
            }
        }
        private global::System.String _Token;
        partial void OnTokenChanging(global::System.String value);
        partial void OnTokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TokenScadenza
        {
            get
            {
                return _TokenScadenza;
            }
            set
            {
                OnTokenScadenzaChanging(value);
                ReportPropertyChanging("TokenScadenza");
                _TokenScadenza = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TokenScadenza");
                OnTokenScadenzaChanged();
            }
        }
        private Nullable<global::System.DateTime> _TokenScadenza;
        partial void OnTokenScadenzaChanging(Nullable<global::System.DateTime> value);
        partial void OnTokenScadenzaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Eliminato
        {
            get
            {
                return _Eliminato;
            }
            set
            {
                OnEliminatoChanging(value);
                ReportPropertyChanging("Eliminato");
                _Eliminato = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Eliminato");
                OnEliminatoChanged();
            }
        }
        private Nullable<global::System.Boolean> _Eliminato;
        partial void OnEliminatoChanging(Nullable<global::System.Boolean> value);
        partial void OnEliminatoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StAperto10
        {
            get
            {
                return _StAperto10;
            }
            set
            {
                OnStAperto10Changing(value);
                ReportPropertyChanging("StAperto10");
                _StAperto10 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StAperto10");
                OnStAperto10Changed();
            }
        }
        private Nullable<global::System.DateTime> _StAperto10;
        partial void OnStAperto10Changing(Nullable<global::System.DateTime> value);
        partial void OnStAperto10Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StPagato20
        {
            get
            {
                return _StPagato20;
            }
            set
            {
                OnStPagato20Changing(value);
                ReportPropertyChanging("StPagato20");
                _StPagato20 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StPagato20");
                OnStPagato20Changed();
            }
        }
        private Nullable<global::System.DateTime> _StPagato20;
        partial void OnStPagato20Changing(Nullable<global::System.DateTime> value);
        partial void OnStPagato20Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StInvioBozza30
        {
            get
            {
                return _StInvioBozza30;
            }
            set
            {
                OnStInvioBozza30Changing(value);
                ReportPropertyChanging("StInvioBozza30");
                _StInvioBozza30 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StInvioBozza30");
                OnStInvioBozza30Changed();
            }
        }
        private Nullable<global::System.DateTime> _StInvioBozza30;
        partial void OnStInvioBozza30Changing(Nullable<global::System.DateTime> value);
        partial void OnStInvioBozza30Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StRicezioneFile40
        {
            get
            {
                return _StRicezioneFile40;
            }
            set
            {
                OnStRicezioneFile40Changing(value);
                ReportPropertyChanging("StRicezioneFile40");
                _StRicezioneFile40 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StRicezioneFile40");
                OnStRicezioneFile40Changed();
            }
        }
        private Nullable<global::System.DateTime> _StRicezioneFile40;
        partial void OnStRicezioneFile40Changing(Nullable<global::System.DateTime> value);
        partial void OnStRicezioneFile40Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StAttesaSpedizione50
        {
            get
            {
                return _StAttesaSpedizione50;
            }
            set
            {
                OnStAttesaSpedizione50Changing(value);
                ReportPropertyChanging("StAttesaSpedizione50");
                _StAttesaSpedizione50 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StAttesaSpedizione50");
                OnStAttesaSpedizione50Changed();
            }
        }
        private Nullable<global::System.DateTime> _StAttesaSpedizione50;
        partial void OnStAttesaSpedizione50Changing(Nullable<global::System.DateTime> value);
        partial void OnStAttesaSpedizione50Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StSpedito60
        {
            get
            {
                return _StSpedito60;
            }
            set
            {
                OnStSpedito60Changing(value);
                ReportPropertyChanging("StSpedito60");
                _StSpedito60 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StSpedito60");
                OnStSpedito60Changed();
            }
        }
        private Nullable<global::System.DateTime> _StSpedito60;
        partial void OnStSpedito60Changing(Nullable<global::System.DateTime> value);
        partial void OnStSpedito60Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StChiuso70
        {
            get
            {
                return _StChiuso70;
            }
            set
            {
                OnStChiuso70Changing(value);
                ReportPropertyChanging("StChiuso70");
                _StChiuso70 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StChiuso70");
                OnStChiuso70Changed();
            }
        }
        private Nullable<global::System.DateTime> _StChiuso70;
        partial void OnStChiuso70Changing(Nullable<global::System.DateTime> value);
        partial void OnStChiuso70Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SpedTipo
        {
            get
            {
                return _SpedTipo;
            }
            set
            {
                OnSpedTipoChanging(value);
                ReportPropertyChanging("SpedTipo");
                _SpedTipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SpedTipo");
                OnSpedTipoChanged();
            }
        }
        private Nullable<global::System.Int32> _SpedTipo;
        partial void OnSpedTipoChanging(Nullable<global::System.Int32> value);
        partial void OnSpedTipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Spedriserva
        {
            get
            {
                return _Spedriserva;
            }
            set
            {
                OnSpedriservaChanging(value);
                ReportPropertyChanging("Spedriserva");
                _Spedriserva = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Spedriserva");
                OnSpedriservaChanged();
            }
        }
        private Nullable<global::System.Int32> _Spedriserva;
        partial void OnSpedriservaChanging(Nullable<global::System.Int32> value);
        partial void OnSpedriservaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SpedNome
        {
            get
            {
                return _SpedNome;
            }
            set
            {
                OnSpedNomeChanging(value);
                ReportPropertyChanging("SpedNome");
                _SpedNome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SpedNome");
                OnSpedNomeChanged();
            }
        }
        private global::System.String _SpedNome;
        partial void OnSpedNomeChanging(global::System.String value);
        partial void OnSpedNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SpedCognome
        {
            get
            {
                return _SpedCognome;
            }
            set
            {
                OnSpedCognomeChanging(value);
                ReportPropertyChanging("SpedCognome");
                _SpedCognome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SpedCognome");
                OnSpedCognomeChanged();
            }
        }
        private global::System.String _SpedCognome;
        partial void OnSpedCognomeChanging(global::System.String value);
        partial void OnSpedCognomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SpedIndirizzo
        {
            get
            {
                return _SpedIndirizzo;
            }
            set
            {
                OnSpedIndirizzoChanging(value);
                ReportPropertyChanging("SpedIndirizzo");
                _SpedIndirizzo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SpedIndirizzo");
                OnSpedIndirizzoChanged();
            }
        }
        private global::System.String _SpedIndirizzo;
        partial void OnSpedIndirizzoChanging(global::System.String value);
        partial void OnSpedIndirizzoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SpedCitta
        {
            get
            {
                return _SpedCitta;
            }
            set
            {
                OnSpedCittaChanging(value);
                ReportPropertyChanging("SpedCitta");
                _SpedCitta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SpedCitta");
                OnSpedCittaChanged();
            }
        }
        private global::System.String _SpedCitta;
        partial void OnSpedCittaChanging(global::System.String value);
        partial void OnSpedCittaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> GiornoLaurea
        {
            get
            {
                return _GiornoLaurea;
            }
            set
            {
                OnGiornoLaureaChanging(value);
                ReportPropertyChanging("GiornoLaurea");
                _GiornoLaurea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GiornoLaurea");
                OnGiornoLaureaChanged();
            }
        }
        private Nullable<global::System.DateTime> _GiornoLaurea;
        partial void OnGiornoLaureaChanging(Nullable<global::System.DateTime> value);
        partial void OnGiornoLaureaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SpedCAP
        {
            get
            {
                return _SpedCAP;
            }
            set
            {
                OnSpedCAPChanging(value);
                ReportPropertyChanging("SpedCAP");
                _SpedCAP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SpedCAP");
                OnSpedCAPChanged();
            }
        }
        private global::System.String _SpedCAP;
        partial void OnSpedCAPChanging(global::System.String value);
        partial void OnSpedCAPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CodFiscalePersonale
        {
            get
            {
                return _CodFiscalePersonale;
            }
            set
            {
                OnCodFiscalePersonaleChanging(value);
                ReportPropertyChanging("CodFiscalePersonale");
                _CodFiscalePersonale = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CodFiscalePersonale");
                OnCodFiscalePersonaleChanged();
            }
        }
        private global::System.String _CodFiscalePersonale;
        partial void OnCodFiscalePersonaleChanging(global::System.String value);
        partial void OnCodFiscalePersonaleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StampeBN
        {
            get
            {
                return _StampeBN;
            }
            set
            {
                OnStampeBNChanging(value);
                ReportPropertyChanging("StampeBN");
                _StampeBN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StampeBN");
                OnStampeBNChanged();
            }
        }
        private Nullable<global::System.Int32> _StampeBN;
        partial void OnStampeBNChanging(Nullable<global::System.Int32> value);
        partial void OnStampeBNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StampeColori
        {
            get
            {
                return _StampeColori;
            }
            set
            {
                OnStampeColoriChanging(value);
                ReportPropertyChanging("StampeColori");
                _StampeColori = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StampeColori");
                OnStampeColoriChanged();
            }
        }
        private Nullable<global::System.Int32> _StampeColori;
        partial void OnStampeColoriChanging(Nullable<global::System.Int32> value);
        partial void OnStampeColoriChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CostoBN
        {
            get
            {
                return _CostoBN;
            }
            set
            {
                OnCostoBNChanging(value);
                ReportPropertyChanging("CostoBN");
                _CostoBN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CostoBN");
                OnCostoBNChanged();
            }
        }
        private Nullable<global::System.Decimal> _CostoBN;
        partial void OnCostoBNChanging(Nullable<global::System.Decimal> value);
        partial void OnCostoBNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CostoCOLORI
        {
            get
            {
                return _CostoCOLORI;
            }
            set
            {
                OnCostoCOLORIChanging(value);
                ReportPropertyChanging("CostoCOLORI");
                _CostoCOLORI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CostoCOLORI");
                OnCostoCOLORIChanged();
            }
        }
        private Nullable<global::System.Decimal> _CostoCOLORI;
        partial void OnCostoCOLORIChanging(Nullable<global::System.Decimal> value);
        partial void OnCostoCOLORIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CostoSpedizione
        {
            get
            {
                return _CostoSpedizione;
            }
            set
            {
                OnCostoSpedizioneChanging(value);
                ReportPropertyChanging("CostoSpedizione");
                _CostoSpedizione = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CostoSpedizione");
                OnCostoSpedizioneChanged();
            }
        }
        private Nullable<global::System.Decimal> _CostoSpedizione;
        partial void OnCostoSpedizioneChanging(Nullable<global::System.Decimal> value);
        partial void OnCostoSpedizioneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CostoFisso
        {
            get
            {
                return _CostoFisso;
            }
            set
            {
                OnCostoFissoChanging(value);
                ReportPropertyChanging("CostoFisso");
                _CostoFisso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CostoFisso");
                OnCostoFissoChanged();
            }
        }
        private Nullable<global::System.Decimal> _CostoFisso;
        partial void OnCostoFissoChanging(Nullable<global::System.Decimal> value);
        partial void OnCostoFissoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TipoRillegatura
        {
            get
            {
                return _TipoRillegatura;
            }
            set
            {
                OnTipoRillegaturaChanging(value);
                ReportPropertyChanging("TipoRillegatura");
                _TipoRillegatura = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TipoRillegatura");
                OnTipoRillegaturaChanged();
            }
        }
        private Nullable<global::System.Int32> _TipoRillegatura;
        partial void OnTipoRillegaturaChanging(Nullable<global::System.Int32> value);
        partial void OnTipoRillegaturaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CostoRillegatura
        {
            get
            {
                return _CostoRillegatura;
            }
            set
            {
                OnCostoRillegaturaChanging(value);
                ReportPropertyChanging("CostoRillegatura");
                _CostoRillegatura = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CostoRillegatura");
                OnCostoRillegaturaChanged();
            }
        }
        private Nullable<global::System.Decimal> _CostoRillegatura;
        partial void OnCostoRillegaturaChanging(Nullable<global::System.Decimal> value);
        partial void OnCostoRillegaturaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean BozzaAcquistata
        {
            get
            {
                return _BozzaAcquistata;
            }
            set
            {
                OnBozzaAcquistataChanging(value);
                ReportPropertyChanging("BozzaAcquistata");
                _BozzaAcquistata = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BozzaAcquistata");
                OnBozzaAcquistataChanged();
            }
        }
        private global::System.Boolean _BozzaAcquistata;
        partial void OnBozzaAcquistataChanging(global::System.Boolean value);
        partial void OnBozzaAcquistataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CostoBozza
        {
            get
            {
                return _CostoBozza;
            }
            set
            {
                OnCostoBozzaChanging(value);
                ReportPropertyChanging("CostoBozza");
                _CostoBozza = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CostoBozza");
                OnCostoBozzaChanged();
            }
        }
        private Nullable<global::System.Decimal> _CostoBozza;
        partial void OnCostoBozzaChanging(Nullable<global::System.Decimal> value);
        partial void OnCostoBozzaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IVA
        {
            get
            {
                return _IVA;
            }
            set
            {
                OnIVAChanging(value);
                ReportPropertyChanging("IVA");
                _IVA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IVA");
                OnIVAChanged();
            }
        }
        private Nullable<global::System.Int32> _IVA;
        partial void OnIVAChanging(Nullable<global::System.Int32> value);
        partial void OnIVAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CostoTotale
        {
            get
            {
                return _CostoTotale;
            }
            set
            {
                OnCostoTotaleChanging(value);
                ReportPropertyChanging("CostoTotale");
                _CostoTotale = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CostoTotale");
                OnCostoTotaleChanged();
            }
        }
        private Nullable<global::System.Decimal> _CostoTotale;
        partial void OnCostoTotaleChanging(Nullable<global::System.Decimal> value);
        partial void OnCostoTotaleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FatturaEmessa
        {
            get
            {
                return _FatturaEmessa;
            }
            set
            {
                OnFatturaEmessaChanging(value);
                ReportPropertyChanging("FatturaEmessa");
                _FatturaEmessa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FatturaEmessa");
                OnFatturaEmessaChanged();
            }
        }
        private Nullable<global::System.DateTime> _FatturaEmessa;
        partial void OnFatturaEmessaChanging(Nullable<global::System.DateTime> value);
        partial void OnFatturaEmessaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CopieStampare
        {
            get
            {
                return _CopieStampare;
            }
            set
            {
                OnCopieStampareChanging(value);
                ReportPropertyChanging("CopieStampare");
                _CopieStampare = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CopieStampare");
                OnCopieStampareChanged();
            }
        }
        private Nullable<global::System.Int32> _CopieStampare;
        partial void OnCopieStampareChanging(Nullable<global::System.Int32> value);
        partial void OnCopieStampareChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean CartaPlus
        {
            get
            {
                return _CartaPlus;
            }
            set
            {
                OnCartaPlusChanging(value);
                ReportPropertyChanging("CartaPlus");
                _CartaPlus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CartaPlus");
                OnCartaPlusChanged();
            }
        }
        private global::System.Boolean _CartaPlus;
        partial void OnCartaPlusChanging(global::System.Boolean value);
        partial void OnCartaPlusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean FronteRetro
        {
            get
            {
                return _FronteRetro;
            }
            set
            {
                OnFronteRetroChanging(value);
                ReportPropertyChanging("FronteRetro");
                _FronteRetro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FronteRetro");
                OnFronteRetroChanged();
            }
        }
        private global::System.Boolean _FronteRetro;
        partial void OnFronteRetroChanging(global::System.Boolean value);
        partial void OnFronteRetroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cellulare
        {
            get
            {
                return _Cellulare;
            }
            set
            {
                OnCellulareChanging(value);
                ReportPropertyChanging("Cellulare");
                _Cellulare = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cellulare");
                OnCellulareChanged();
            }
        }
        private global::System.String _Cellulare;
        partial void OnCellulareChanging(global::System.String value);
        partial void OnCellulareChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CostoCartaPlus
        {
            get
            {
                return _CostoCartaPlus;
            }
            set
            {
                OnCostoCartaPlusChanging(value);
                ReportPropertyChanging("CostoCartaPlus");
                _CostoCartaPlus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CostoCartaPlus");
                OnCostoCartaPlusChanged();
            }
        }
        private Nullable<global::System.Decimal> _CostoCartaPlus;
        partial void OnCostoCartaPlusChanging(Nullable<global::System.Decimal> value);
        partial void OnCostoCartaPlusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PagamentoId
        {
            get
            {
                return _PagamentoId;
            }
            set
            {
                OnPagamentoIdChanging(value);
                ReportPropertyChanging("PagamentoId");
                _PagamentoId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PagamentoId");
                OnPagamentoIdChanged();
            }
        }
        private global::System.String _PagamentoId;
        partial void OnPagamentoIdChanging(global::System.String value);
        partial void OnPagamentoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Note
        {
            get
            {
                return _Note;
            }
            set
            {
                OnNoteChanging(value);
                ReportPropertyChanging("Note");
                _Note = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Note");
                OnNoteChanged();
            }
        }
        private global::System.String _Note;
        partial void OnNoteChanging(global::System.String value);
        partial void OnNoteChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Tesi", "FilesOFOrder", "File")]
        public EntityCollection<File> File
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<File>("Tesi.FilesOFOrder", "File");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<File>("Tesi.FilesOFOrder", "File", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Tesi", "RilegaturaOrdine", "Rilegatura")]
        public Rilegatura Rilegatura
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rilegatura>("Tesi.RilegaturaOrdine", "Rilegatura").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rilegatura>("Tesi.RilegaturaOrdine", "Rilegatura").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Rilegatura> RilegaturaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rilegatura>("Tesi.RilegaturaOrdine", "Rilegatura");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Rilegatura>("Tesi.RilegaturaOrdine", "Rilegatura", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Tesi", "SpedizioneOrdine", "Spediz")]
        public Spediz Spediz
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Spediz>("Tesi.SpedizioneOrdine", "Spediz").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Spediz>("Tesi.SpedizioneOrdine", "Spediz").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Spediz> SpedizReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Spediz>("Tesi.SpedizioneOrdine", "Spediz");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Spediz>("Tesi.SpedizioneOrdine", "Spediz", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Tesi", Name="Rilegatura")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Rilegatura : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Rilegatura object.
        /// </summary>
        /// <param name="rilegaturaID">Initial value of the RilegaturaID property.</param>
        /// <param name="delete">Initial value of the delete property.</param>
        public static Rilegatura CreateRilegatura(global::System.Int32 rilegaturaID, global::System.Boolean delete)
        {
            Rilegatura rilegatura = new Rilegatura();
            rilegatura.RilegaturaID = rilegaturaID;
            rilegatura.delete = delete;
            return rilegatura;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RilegaturaID
        {
            get
            {
                return _RilegaturaID;
            }
            set
            {
                if (_RilegaturaID != value)
                {
                    OnRilegaturaIDChanging(value);
                    ReportPropertyChanging("RilegaturaID");
                    _RilegaturaID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RilegaturaID");
                    OnRilegaturaIDChanged();
                }
            }
        }
        private global::System.Int32 _RilegaturaID;
        partial void OnRilegaturaIDChanging(global::System.Int32 value);
        partial void OnRilegaturaIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titolo
        {
            get
            {
                return _Titolo;
            }
            set
            {
                OnTitoloChanging(value);
                ReportPropertyChanging("Titolo");
                _Titolo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Titolo");
                OnTitoloChanged();
            }
        }
        private global::System.String _Titolo;
        partial void OnTitoloChanging(global::System.String value);
        partial void OnTitoloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descrizione
        {
            get
            {
                return _Descrizione;
            }
            set
            {
                OnDescrizioneChanging(value);
                ReportPropertyChanging("Descrizione");
                _Descrizione = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descrizione");
                OnDescrizioneChanged();
            }
        }
        private global::System.String _Descrizione;
        partial void OnDescrizioneChanging(global::System.String value);
        partial void OnDescrizioneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Foto
        {
            get
            {
                return _Foto;
            }
            set
            {
                OnFotoChanging(value);
                ReportPropertyChanging("Foto");
                _Foto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Foto");
                OnFotoChanged();
            }
        }
        private global::System.String _Foto;
        partial void OnFotoChanging(global::System.String value);
        partial void OnFotoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean delete
        {
            get
            {
                return _delete;
            }
            set
            {
                OndeleteChanging(value);
                ReportPropertyChanging("delete");
                _delete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("delete");
                OndeleteChanged();
            }
        }
        private global::System.Boolean _delete;
        partial void OndeleteChanging(global::System.Boolean value);
        partial void OndeleteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Costo
        {
            get
            {
                return _Costo;
            }
            set
            {
                OnCostoChanging(value);
                ReportPropertyChanging("Costo");
                _Costo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Costo");
                OnCostoChanged();
            }
        }
        private Nullable<global::System.Decimal> _Costo;
        partial void OnCostoChanging(Nullable<global::System.Decimal> value);
        partial void OnCostoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Tesi", "RilegaturaOrdine", "Ordine")]
        public EntityCollection<Ordine> Ordine
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ordine>("Tesi.RilegaturaOrdine", "Ordine");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ordine>("Tesi.RilegaturaOrdine", "Ordine", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Tesi", Name="Spediz")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Spediz : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Spediz object.
        /// </summary>
        /// <param name="spedizID">Initial value of the SpedizID property.</param>
        /// <param name="deleted">Initial value of the deleted property.</param>
        public static Spediz CreateSpediz(global::System.Int32 spedizID, global::System.Boolean deleted)
        {
            Spediz spediz = new Spediz();
            spediz.SpedizID = spedizID;
            spediz.deleted = deleted;
            return spediz;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SpedizID
        {
            get
            {
                return _SpedizID;
            }
            set
            {
                if (_SpedizID != value)
                {
                    OnSpedizIDChanging(value);
                    ReportPropertyChanging("SpedizID");
                    _SpedizID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SpedizID");
                    OnSpedizIDChanged();
                }
            }
        }
        private global::System.Int32 _SpedizID;
        partial void OnSpedizIDChanging(global::System.Int32 value);
        partial void OnSpedizIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titolo
        {
            get
            {
                return _Titolo;
            }
            set
            {
                OnTitoloChanging(value);
                ReportPropertyChanging("Titolo");
                _Titolo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Titolo");
                OnTitoloChanged();
            }
        }
        private global::System.String _Titolo;
        partial void OnTitoloChanging(global::System.String value);
        partial void OnTitoloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descrizione
        {
            get
            {
                return _Descrizione;
            }
            set
            {
                OnDescrizioneChanging(value);
                ReportPropertyChanging("Descrizione");
                _Descrizione = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descrizione");
                OnDescrizioneChanged();
            }
        }
        private global::System.String _Descrizione;
        partial void OnDescrizioneChanging(global::System.String value);
        partial void OnDescrizioneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Prezzo
        {
            get
            {
                return _Prezzo;
            }
            set
            {
                OnPrezzoChanging(value);
                ReportPropertyChanging("Prezzo");
                _Prezzo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prezzo");
                OnPrezzoChanged();
            }
        }
        private Nullable<global::System.Decimal> _Prezzo;
        partial void OnPrezzoChanging(Nullable<global::System.Decimal> value);
        partial void OnPrezzoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean deleted
        {
            get
            {
                return _deleted;
            }
            set
            {
                OndeletedChanging(value);
                ReportPropertyChanging("deleted");
                _deleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("deleted");
                OndeletedChanged();
            }
        }
        private global::System.Boolean _deleted;
        partial void OndeletedChanging(global::System.Boolean value);
        partial void OndeletedChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Tesi", "SpedizioneOrdine", "Ordine")]
        public EntityCollection<Ordine> Ordine
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ordine>("Tesi.SpedizioneOrdine", "Ordine");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ordine>("Tesi.SpedizioneOrdine", "Ordine", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
